# Generated by Django 4.1.2 on 2023-01-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PredictSNPJobModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("job_id", models.CharField(max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("root_folder", models.CharField(default="Unknown", max_length=60)),
            ],
            options={
                "db_table": "predict_snp_jobs",
            },
        ),
    ]
